[font]
size = 12.5

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window.padding]
x = 15
y = 15

# [window]
# opacity = 0.7

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
